name       : cpd
version    : 0.5.3
release    : 1
source     :
    - https://github.com/gadomski/cpd/archive/refs/tags/v0.5.3.tar.gz : d5230b2c20f2b3f3400b42a099efe937008eabf06b281484090d250f12529e8c
homepage   : https://www.gadom.ski/cpd/
license    : GPL-2.0-or-later
component  : programming.library
summary    : C++ implementation of the Coherent Point Drift point set registration algorithm
description: |
    Coherent Point Drift (CPD) is a point-set registration algorithm, originally developed by Andriy Myronenko et al. This is a C++ library that runs CPD.
    CPD can be compared to Iterative Closest Point, another point-set registration algorithm that is widely used. While ICP minimizes point-to-point distances, CPD uses a Gaussian Mixture Model to minimize the error between a point and all other points.
avx2       : yes
builddeps  :
    - pkgconfig(eigen3)
    - pkgconfig(jsoncpp)
    - fgt-devel
setup      : |
    %patch -p1 < $pkgfiles/build-shared-lib.patch
    %patch -p1 < $pkgfiles/find-fgt-correctly.patch
    %cmake_ninja \
        -DBUILD_SHARED_LIBS=ON \
        -DEIGEN3_INCLUDE_DIR=/usr/include/eigen3
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    if [[ -z "${AVX2BUILD}" ]]; then
        %ninja_check
    fi
